// raw → 1시간 평균 (버킷 이름은 InfluxInitializer가 설정값으로 치환)
from(bucket: "${rawBucket}")
    |> range(start: -1h)
    |> filter(fn: (r) => r._field == "value")
    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)
    |> to(bucket: "${avg1hBucket}")
