// 1시간 평균 → 1일 평균 (스케줄 every=1d은 태스크 메타데이터에 저장됨)
from(bucket: "omagotchi-avg-1h")
    |> range(start: -1d)
    |> filter(fn: (r) => r._field == "value")
    |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)
    |> to(bucket: "omagotchi-avg-1d")
