// raw → 1시간 평균 (스케줄 every=1h은 태스크 메타데이터에 저장됨)
from(bucket: "omagotchi-raw")
    |> range(start: -1h)
    |> filter(fn: (r) => r._field == "value")
    |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)
    |> to(bucket: "omagotchi-avg-1h")
